In [2]:
from sympy import *
init_printing(use_unicode=True)

In [3]:
import numpy as np
def anglgeAxisToRotationMatrix(m_angle, m_axis):
    res = np.zeros(3,3)
    sin_axis  = sin(m_angle) * m_axis;
    c = cos(m_angle);
    cos1_axis = (1.0-c) * m_axis;

    tmp = cos1_axis[0]* m_axis[1]
    res[0,1] = tmp - sin_axis[2]
    res[1,0] = tmp + sin_axis[2]

    tmp = cos1_axis.x() * m_axis[2]
    res[0,2] = tmp + sin_axis[1]
    res[2,0] = tmp - sin_axis[1]

    tmp = cos1_axis.y() * m_axis[2]
    res[1,2] = tmp - sin_axis[1]
    res[2,1] = tmp + sin_axis[1]

    tmp = (cos1_axis * m_axis) + c
    res[0,0] = tmp[0]
    res[1,1] = tmp[1]
    res[2,2] = tmp[2]
    return res
def eulerToTransform(alpha, beta, gamma):
    c1 = cos(alpha)
    s1 = sin(alpha)
    c2 = cos(beta)
    s2 = sin(beta)
    c3 = cos(gamma)
    s3 = sin(gamma)
    M = [[c2*c3, -c2*s3, s2], [c1*s3 + c3*s1*s2, c1*c3 - s1*s2*s3, -c2*s1], [s1*s3-c1*c3*s2, c3*s1+c1*s2*s3, c1*c2]]
    return M
def paramToHomoTransform(x,y,z, alpha, beta, gamma):
    c1 = cos(alpha)
    s1 = sin(alpha)
    c2 = cos(beta)
    s2 = sin(beta)
    c3 = cos(gamma)
    s3 = sin(gamma)
    M = [[c2*c3, -c2*s3, s2, x], 
         [c1*s3 + c3*s1*s2, c1*c3 - s1*s2*s3, -c2*s1, y], 
         [s1*s3-c1*c3*s2, c3*s1+c1*s2*s3, c1*c2, z],
         [0.0, 0.0, 0.0, 1.0]]
    return M

In [4]:
from scipy.spatial.transform import Rotation as R 
r = R.from_euler('XYZ',[1.0,0.2,0.1])
print(r.as_dcm())
print(eulerToTransform(1.0,0.2,0.1))

[[ 0.97517033 -0.0978434   0.19866933]
 [ 0.22027953  0.52091345 -0.82469759]
 [-0.02279831  0.8479834   0.52953223]]
[[0.975170327201816, -0.0978433950072557, 0.198669330795061], [0.220279526593223, 0.520913445589612, -0.824697588433375], [-0.0227983137308199, 0.847983403291251, 0.529532231911920]]


In [5]:
x, y, z, a, b, c, r = symbols('x y z a b c r')

In [6]:
P = MatrixSymbol('P', 3, 4)
T_init = MatrixSymbol('T_init', 4, 4)
T = Matrix(paramToHomoTransform(x,y,z,a,b,c))
Q = P * T * T_init

In [16]:
var=c
print("[",diff(paramToHomoTransform(x,y,z,a,b,c)[0][0], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[0][1], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[0][2], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[0][3], var),"]\n",
      "[",diff(paramToHomoTransform(x,y,z,a,b,c)[1][0], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[1][1], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[1][2], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[1][3], var),"]\n",
      "[",diff(paramToHomoTransform(x,y,z,a,b,c)[2][0], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[2][1], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[2][2], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[2][3], var),"]\n",
      "[",diff(paramToHomoTransform(x,y,z,a,b,c)[3][0], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[3][1], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[3][2], var),",",
          diff(paramToHomoTransform(x,y,z,a,b,c)[3][3], var),"]")

[ -sin(c)*cos(b) , -cos(b)*cos(c) , 0 , 0 ]
 [ -sin(a)*sin(b)*sin(c) + cos(a)*cos(c) , -sin(a)*sin(b)*cos(c) - sin(c)*cos(a) , 0 , 0 ]
 [ sin(a)*cos(c) + sin(b)*sin(c)*cos(a) , -sin(a)*sin(c) + sin(b)*cos(a)*cos(c) , 0 , 0 ]
 [ 0 , 0 , 0 , 0 ]


In [48]:
M = Q*Matrix([[1, 0, 0], [0,1,0],[0,0,0],[0,0,1]])

In [49]:
M_inv = M.inverse()

In [50]:
M_inv

                                                                              
⎛  ⎡           cos(b)⋅cos(c)                         -sin(c)⋅cos(b)           
⎜  ⎢                                                                          
⎜  ⎢sin(a)⋅sin(b)⋅cos(c) + sin(c)⋅cos(a)  -sin(a)⋅sin(b)⋅sin(c) + cos(a)⋅cos(c
⎜P⋅⎢                                                                          
⎜  ⎢sin(a)⋅sin(c) - sin(b)⋅cos(a)⋅cos(c)  sin(a)⋅cos(c) + sin(b)⋅sin(c)⋅cos(a)
⎜  ⎢                                                                          
⎝  ⎣                0.0                                    0.0                

                                        -1
       sin(b)       x ⎤       ⎡1  0  0⎤⎞  
                      ⎥       ⎢       ⎥⎟  
)  -sin(a)⋅cos(b)   y ⎥       ⎢0  1  0⎥⎟  
                      ⎥⋅Tᵢₙᵢₜ⋅⎢       ⎥⎟  
   cos(a)⋅cos(b)    z ⎥       ⎢0  0  0⎥⎟  
                      ⎥       ⎢       ⎥⎟  
        0.0        1.0⎦       ⎣0  0  1⎦⎠  

In [51]:
x_image, y_image = symbols("x_image y_image")

In [52]:
unnorm_p_plane = M_inv * Matrix([[x_image], [y_image], [1.0]])

In [53]:
w_norm = (M_inv * Matrix([[x_image], [y_image], [1.0]]))[2,0]

In [54]:
p_plane = unnorm_p_plane / w_norm

In [55]:
res = p_plane[0,0] * p_plane[0,0]  / (r*r) + p_plane[1,0] * p_plane[1,0] / (r*r) - 1.0

                                                                              
        ⎛        ⎛                                                            
        ⎜        ⎜⎛  ⎡           cos(b)⋅cos(c)                         -sin(c)
        ⎜        ⎜⎜  ⎢                                                        
        ⎜        ⎜⎜  ⎢sin(a)⋅sin(b)⋅cos(c) + sin(c)⋅cos(a)  -sin(a)⋅sin(b)⋅sin
        ⎜x_image⋅⎜⎜P⋅⎢                                                        
        ⎜        ⎜⎜  ⎢sin(a)⋅sin(c) - sin(b)⋅cos(a)⋅cos(c)  sin(a)⋅cos(c) + si
        ⎜        ⎜⎜  ⎢                                                        
        ⎝        ⎝⎝  ⎣                0.0                                    0
-1.0 + ───────────────────────────────────────────────────────────────────────
                                                                              
          ⎛        ⎛                                                          
          ⎜        ⎜⎛  ⎡           cos(b)⋅cos(c)    

In [62]:
sympify(res).diff(y)